#!/usr/bin/env python3

import logging
from logging import StreamHandler, Formatter

import sys

from argparse import ArgumentParser

from pynoter import Server


if __name__ == "__main__":
    # Initialize logging.
    logger = logging.getLogger('pynoter')
    handler = StreamHandler()
    logger.addHandler(handler)

    # Command line argument parsing.
    commands = ArgumentParser(description="Advanced Notification Daemon")

    # Debugging output.
    commands.add_argument("--debug", "-D", action="store_true", default=False,
            dest="debug", help="Show debug information.")

    # Use system bus instead of session bus.
    commands.add_argument("--system", "-S", action="store_true", default=False,
            dest="system", help="Use system bus instead of session bus.")

    # Use a special bus suffix for the server.
    commands.add_argument("--bus_suffix", "-B", action="store", default=None,
            dest="bus_suffix", help="The suffix which should be added to the" +
            " servers bus name.")

    # Parse arguments
    parsed_args = commands.parse_args()
    debug = parsed_args.debug
    use_system = parsed_args.system
    bus_suffix = parsed_args.bus_suffix

    # Set options accordingly.
    if debug:
        logger.setLevel(logging.DEBUG)
        formatter = Formatter(
                fmt="%(asctime)s - %(name)s:%(lineno)d -- %(levelname)s:%(message)s",
                datefmt="%Y-%m-%d %H:%M:%S")
        handler.setFormatter(formatter)
    else:
        logger.setLevel(logging.WARNING)
        formatter = Formatter(
                fmt="%(asctime)s -- %(message)s",
                datefmt="%Y-%m-%d %H:%M:%S")
        handler.setFormatter(formatter)

    # Start the server.
    print("Start server now...")

    try:
        server = Server(bus_suffix=bus_suffix, use_system_bus=use_system)
        server.run()
    except Exception as e:
        print(str(e))

        sys.exit(1)
